### ISSUE TITLE
Erläuterung der Abwägung der gewählten Methoden im Vorgehen

### ISSUE THREAD

**Issue by Hayanik** [Roba42/EPWS2324-BrachtendorfHayaniKraft#14]

**Comment by Hayanik** [comment]
Vorteile automatisierter Lösungen:
Zeitersparnis: Automatisierte Tests können innerhalb von Minuten durchgeführt werden, während manuelle Tests Tage oder Wochen in Anspruch nehmen können, je nach Komplexität der Website.
Konsistenz: Automatisierung gewährleistet, dass jeder Test unter identischen Bedingungen durchgeführt wird, was eine gleichbleibende Qualität und Objektivität sicherstellt.
Kosteneffizienz: Die initiale Investition in automatisierte Testverfahren ist zwar höher, aber auf lange Sicht sind sie kostengünstiger, da sie weniger personelle Ressourcen erfordern und häufiger ohne zusätzliche Kosten wiederholt werden können.
Skalierbarkeit: Automatisierte Systeme können leicht an eine zunehmende Anzahl von Webseiten oder größere Inhalte angepasst werden, ohne dass der Ressourceneinsatz proportional ansteigt.
Fortlaufende Überwachung: Sie ermöglichen eine kontinuierliche Überwachung der Barrierefreiheit, was besonders wichtig ist, da sich Websites dynamisch verändern und aktualisieren.

Erweiterung mit KI und ML:
Adaptive Lernfähigkeit: Durch die Implementierung von ML können unsere automatisierten Tests aus früheren Durchläufen lernen, was zu einer stetigen Verbesserung der Testgenauigkeit führt.
Verständnis komplexer Muster: KI kann dabei helfen, subtile Barrieren zu identifizieren, die durch standardisierte Tests möglicherweise übersehen werden.
Vorhersage zukünftiger Barrieren: Mit KI könnten potenzielle zukünftige Barrierefreiheitsprobleme vorhergesagt werden, basierend auf den sich entwickelnden Webstandards und Benutzeranforderungen.
Limitationen manueller Tests und deren Auswirkungen:
Skalierungsprobleme: Manuelle Tests sind schwer zu skalieren, da jede zusätzliche Webseite die direkte Beteiligung eines Testers erfordert.
Subjektivität: Die Qualität manueller Tests kann variieren, da sie von der Expertise und dem Urteilsvermögen des Testers abhängig sind.
Zeit- und Kostenaufwand: Manuelle Tests sind zeitaufwändig und erfordern fortlaufend finanzielle Mittel für Tester, was sie für regelmäßige Prüfungen ungeeignet macht.
Verzögerungen bei der Auslieferung: Die Dauer manueller Tests kann die schnelle Auslieferung von Webinhalten behindern, was besonders in einem schnelllebigen digitalen Umfeld problematisch ist.

**Comment by Clemix21** [comment]
6h
