### ISSUE TITLE
Darstellung der Implementierung der modellierten Konzepte anhand der Demonstration des funktionalen Prototypes

### ISSUE THREAD

**Issue by Roba42** [Roba42/EPWS2324-BrachtendorfHayaniKraft#29]

**Comment by Clemix21** [comment]
Rapid Prototype/V2.0_Python.py
Rapid Prototype/v2.1_Azure_Generate_ALT_TAGS.py
Main Prototype/Accesstra.py

Iterationen des Prototypes zum Generieren von fehlenden Alt-Tags.
60h
