### ISSUE TITLE
Mögliche Artefakte 

### ISSUE THREAD

**Issue by Roba42** [Roba42/EPWS2324-BrachtendorfHayaniKraft#6]
Hier eine unvollständige Liste von Beispielen weiterer Artefakte, die unabhängig von der Fachperspektive sind und entwickelt werden können:

@Clemix21 @Hayanik 

- [x] Problembeschreibung (auch mittels Fishbone-Diagram)
- [x] Marktrecherche
- [x] Alleinstellungsmerkmale
- [x] Vision
- [x] Wesentliche Anwendungsobjekte
- [x] Rapid Prototype
- [x] Zielhierarchie
- [x] Implementierung (vertikaler Prototyp für Alleinstellungsmerkmale und Anwendungslogik)
- [x] Fazit
- [x] Prozessassessement
- [x] ...

**Comment by Clemix21** [comment]
Checkliste
