### ISSUE TITLE
Kernspezifische Fragen im Wiki hinzufügen

### ISSUE THREAD

**Issue by Roba42** [Roba42/EPWS2324-BrachtendorfHayaniKraft#7]
- [x] Welche Erfordernisse liegen in der Anwendungsdomäne vor?
- [x] Welche Einflüsse (positive sowie negative Auswirkungen, Chancen und Gefahren/Bedrohungen) auf die Nutzungskontexte werden durch die Bereitstellung des zukünftigen Systems insbesondere mit Bezug auf die Ziele Nachhaltiger Entwicklung der Vereinten Nationen erwartet?
- [x] Welche funktionalen und qualitativen Anforderungen können aus den Erfordernissen abgeleitet werden? 
- [x] Welche funktionalen und qualitativen Anforderungen können aus den Erfordernissen abgeleitet werden?
- [x] Wie ist das konzeptuelle Modell ausgestaltet? Welche Bezüge existieren bzgl. der Entwicklungsziele?
- [x] Wie interagieren die zukünftigen Nutzer mit den im System repräsentieren Objekten (Interaktionskonzept) und welche Anwendungslogik ist systemseitig dazu hinterlegt?
- [x] Wie ist der Prototyp/die Prototypen der Benutzungsschnittstelle ausgestaltet (Interface-Design)?
Welchen Erfüllungsgrad weist das Interaktions- und Interface-Design hinsichtlich Zugänglichkeit auf (European Accessibility Act)?
- [x] Welche Anwendungslogik (keine I/O) wurde implementiert und wie „zahlt“ diese auf die Ziele der NutzerInnen ein?
- [x] Nach welchen Kriterien wurden die Evaluation-Methoden und -Techniken ausgewählt und kombiniert?
- [x] Welches sind die Evaluationsergebnisse, welchen Erfüllungsgrad der Entwicklungsziele weisen die finalen Designlösungen auf?
- [x] Welche Konsequenzen ergeben sich daraus für weitere Schritte/Iterationen?

**Comment by Clemix21** [comment]
8h
